# Generated by Django 5.1.1 on 2024-09-18 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earner',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('settings', models.JSONField(default={})),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EarnerHeartBeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('cpu_usage', models.FloatField(null=True)),
                ('memory_usage', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('earner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earnbuddy.earner')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earnbuddy.machine')),
            ],
        ),
        migrations.CreateModel(
            name='MachineHeartBeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docker_version', models.CharField(max_length=128)),
                ('client_version', models.CharField(max_length=128)),
                ('public_ip', models.CharField(max_length=128)),
                ('system_platform', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='earnbuddy.machine')),
            ],
        ),
    ]
