# Generated by Django 5.1.1 on 2024-09-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnbuddy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earnerheartbeat',
            name='cpu_usage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='earnerheartbeat',
            name='memory_usage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='earner',
            name='settings',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='earnerheartbeat',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
