"""initial migrations

Revision ID: e109f81058eb
Revises: 
Create Date: 2024-09-11 19:58:51.451669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e109f81058eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('device_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_ping', sa.DateTime(), nullable=False),
    sa.Column('client_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('public_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('docker_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('system_platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('earner',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientheartusage',
    sa.Column('from_client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('ram_usage', sa.Float(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['from_client_id'], ['client.device_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientheartusage_id'), 'clientheartusage', ['id'], unique=True)
    op.create_table('earnerheartbeat',
    sa.Column('from_client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_earner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('ram_usage', sa.Float(), nullable=True),
    sa.Column('uptime', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_client_id'], ['client.device_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('earnerheartbeat')
    op.drop_index(op.f('ix_clientheartusage_id'), table_name='clientheartusage')
    op.drop_table('clientheartusage')
    op.drop_table('earner')
    op.drop_table('client')
    # ### end Alembic commands ###
